# Generated by Django 5.2 on 2025-05-08 18:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('normalized_signal', models.TextField()),
                ('mask', models.TextField()),
            ],
            options={
                'unique_together': {('name', 'timestamp')},
            },
        ),
        migrations.CreateModel(
            name='SignalFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beat_number', models.IntegerField(default=0)),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('qrs_start', models.IntegerField()),
                ('qrs_end', models.IntegerField()),
                ('p_start', models.IntegerField()),
                ('p_end', models.IntegerField()),
                ('t_start', models.IntegerField()),
                ('t_end', models.IntegerField()),
                ('duree_p_ms', models.FloatField()),
                ('duree_qrs_ms', models.FloatField()),
                ('duree_t_ms', models.FloatField()),
                ('intervalle_pr_ms', models.FloatField()),
                ('intervalle_qt_ms', models.FloatField()),
                ('intervalle_st_ms', models.FloatField()),
                ('p_index', models.IntegerField()),
                ('amplitude_p', models.FloatField()),
                ('r_index', models.IntegerField()),
                ('amplitude_r', models.FloatField()),
                ('intervalle_rr_ms', models.FloatField()),
                ('q_index', models.IntegerField()),
                ('amplitude_q', models.FloatField()),
                ('s_index', models.IntegerField()),
                ('amplitude_s', models.FloatField()),
                ('t_index', models.IntegerField()),
                ('amplitude_t', models.FloatField()),
                ('t_r_ratio', models.FloatField()),
                ('p_r_ratio', models.FloatField()),
                ('qrs_area', models.FloatField()),
                ('slope_qr', models.FloatField()),
                ('slope_rs', models.FloatField()),
                ('p_symmetry', models.FloatField()),
                ('t_inversion', models.IntegerField()),
                ('qrs_axis_estimate', models.FloatField()),
                ('heart_rate_bpm', models.FloatField()),
                ('premature_beat', models.IntegerField()),
                ('local_rr_variability', models.FloatField()),
                ('local_rmssd', models.FloatField()),
                ('bigeminy', models.IntegerField()),
                ('trigeminy', models.IntegerField()),
                ('type', models.CharField(max_length=1)),
                ('signal_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='acquisition.signal')),
            ],
        ),
    ]
