# Generated by Django 5.2 on 2025-05-18 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acquisition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signalfeatures',
            name='PVC_ratio',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='signalfeatures',
            name='QRS_prolonged_ratio',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='signalfeatures',
            name='QT_prolonged_ratio',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='signalfeatures',
            name='count_L',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='signalfeatures',
            name='count_N',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='signalfeatures',
            name='count_R',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='signalfeatures',
            name='count_V',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='signalfeatures',
            name='count_else',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='signalfeatures',
            name='count_slash',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='signalfeatures',
            name='num_beats',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='signalfeatures',
            name='percent_T_inversion',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='signalfeatures',
            name='ratio_L',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='signalfeatures',
            name='ratio_N',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='signalfeatures',
            name='ratio_R',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='signalfeatures',
            name='ratio_V',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='signalfeatures',
            name='ratio_else',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='signalfeatures',
            name='ratio_slash',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='signalfeatures',
            name='std_Intervalle_RR_ms',
            field=models.FloatField(default=0.0),
        ),
    ]
