# Generated by Django 5.2 on 2025-06-02 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acquisition', '0002_signalfeatures_pvc_ratio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beatfeatures',
            name='heart_rate_bpm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='beatfeatures',
            name='intervalle_rr_ms',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='beatfeatures',
            name='p_end',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='beatfeatures',
            name='p_start',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='beatfeatures',
            name='t_end',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='beatfeatures',
            name='t_start',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
